description: 'Run acceptance test on data hosted through tigress-web'
inputs:
  type:
    description: 'Type to run'
    required: true
  chroms:
    description: 'Whether to run all or separate'
    required: true
name: 'Compare with Legacy'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.chroms }}
