name: AcceptanceTests
on: [push, pull_request]

jobs:
  single:
    name: Single Chroms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: No excluded
        uses: ./.github/actions/acceptance_test
        with:
          type: no_exclude
          chroms: separate
      - name: Excluded
        uses: ./.github/actions/acceptance_test
        with:
          type: exclude
          chroms: separate
      - name: Single bed files
        uses: ./.github/actions/acceptance_test
        with:
          type: bed_single
          chroms: separate
      - name: Paired bed files
        uses: ./.github/actions/acceptance_test
        with:
          type: bed_pair
          chroms: separate
  all:
    name: All Chroms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: No excluded
        uses: ./.github/actions/acceptance_test
        with:
          type: no_exclude
          chroms: all
      - name: Excluded
        uses: ./.github/actions/acceptance_test
        with:
          type: exclude
          chroms: all
      - name: Single bed files
        uses: ./.github/actions/acceptance_test
        with:
          type: bed_single
          chroms: all
      - name: Paired bed files
        uses: ./.github/actions/acceptance_test
        with:
          type: bed_pair
          chroms: all
